name: Security Audit

on:
  workflow_call:

jobs:
  audit:
    name: Audit - crate security vulnerabilities
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Running audit
        uses: "rustsec/audit-check@v2.0.0"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
