name: Checking PR title

on:
  workflow_call:
    inputs:
      ignore-labels:
        description: "List of labels to ignore defined as list (new line delimited)"
        default: ""
        type: string

permissions:
  contents: read
  pull-requests: read
  statuses: write

jobs:
  checking-pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          ignoreLabels: inputs.ignore-labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
