name: Checking commit

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:
  checking-commits:
    name: Validate PR commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
